//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: PlayerInitData.proto
namespace ILSnowballFight
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInitData")]
  public partial class PlayerInitData : global::ProtoBuf.IExtensible
  {
    public PlayerInitData() {}
    
    private string _username;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private int _faction;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"faction", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int faction
    {
      get { return _faction; }
      set { _faction = value; }
    }
    private ILSnowballFight.PlayerSyncData _sync;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sync", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ILSnowballFight.PlayerSyncData sync
    {
      get { return _sync; }
      set { _sync = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInitDatas")]
  public partial class PlayerInitDatas : global::ProtoBuf.IExtensible
  {
    public PlayerInitDatas() {}
    
    private readonly global::System.Collections.Generic.List<ILSnowballFight.PlayerInitData> _datas = new global::System.Collections.Generic.List<ILSnowballFight.PlayerInitData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"datas", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ILSnowballFight.PlayerInitData> datas
    {
      get { return _datas; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerSyncData")]
  public partial class PlayerSyncData : global::ProtoBuf.IExtensible
  {
    public PlayerSyncData() {}
    
    private int _userid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private float _xpos;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"xpos", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float xpos
    {
      get { return _xpos; }
      set { _xpos = value; }
    }
    private float _ypos;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ypos", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float ypos
    {
      get { return _ypos; }
      set { _ypos = value; }
    }
    private float _zpos;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"zpos", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float zpos
    {
      get { return _zpos; }
      set { _zpos = value; }
    }
    private float _xrot;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"xrot", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float xrot
    {
      get { return _xrot; }
      set { _xrot = value; }
    }
    private float _yrot;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"yrot", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float yrot
    {
      get { return _yrot; }
      set { _yrot = value; }
    }
    private int _animestate;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"animestate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int animestate
    {
      get { return _animestate; }
      set { _animestate = value; }
    }
    private int _hp;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerSyncDatas")]
  public partial class PlayerSyncDatas : global::ProtoBuf.IExtensible
  {
    public PlayerSyncDatas() {}
    
    private readonly global::System.Collections.Generic.List<ILSnowballFight.PlayerSyncData> _datas = new global::System.Collections.Generic.List<ILSnowballFight.PlayerSyncData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"datas", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ILSnowballFight.PlayerSyncData> datas
    {
      get { return _datas; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PushData")]
  public partial class PushData : global::ProtoBuf.IExtensible
  {
    public PushData() {}
    
    private float _xpos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"xpos", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float xpos
    {
      get { return _xpos; }
      set { _xpos = value; }
    }
    private float _ypos;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ypos", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float ypos
    {
      get { return _ypos; }
      set { _ypos = value; }
    }
    private float _zpos;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"zpos", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float zpos
    {
      get { return _zpos; }
      set { _zpos = value; }
    }
    private float _xrot;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"xrot", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float xrot
    {
      get { return _xrot; }
      set { _xrot = value; }
    }
    private float _yrot;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"yrot", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float yrot
    {
      get { return _yrot; }
      set { _yrot = value; }
    }
    private int _animestate;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"animestate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int animestate
    {
      get { return _animestate; }
      set { _animestate = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FireData")]
  public partial class FireData : global::ProtoBuf.IExtensible
  {
    public FireData() {}
    
    private int _userid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private bool _hit;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"hit", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool hit
    {
      get { return _hit; }
      set { _hit = value; }
    }
    private int _parts;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"parts", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int parts
    {
      get { return _parts; }
      set { _parts = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BlockData")]
  public partial class BlockData : global::ProtoBuf.IExtensible
  {
    public BlockData() {}
    
    private int _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }
    private int _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int y
    {
      get { return _y; }
      set { _y = value; }
    }
    private int _z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int z
    {
      get { return _z; }
      set { _z = value; }
    }
    private int _blocktype;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"blocktype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int blocktype
    {
      get { return _blocktype; }
      set { _blocktype = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}